[buildPlans.Plane]
family = "Plane"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.Plane.variants.design]
six = "closed-contour"
seven = "bend-serifed"
eight = "two-circles"
nine = "closed-contour"
capital-a = "curly-serifless"
capital-k = "straight-serifless"
capital-p = "open-serifless"
capital-r = "standing-open-serifless"
capital-v = "curly-serifless"
capital-w = "straight-vertical-sides-serifless"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "cursive"
a = "single-storey-tailed"
b = "toothless-corner-serifless"
d = "toothless-corner-serifless"
e = "rounded"
h = "tailed-serifless"
k = "straight-bottom-right-serifed"
m = "earless-rounded-double-arch-short-leg-tailed-serifless"
n = "earless-rounded-tailed-serifless"
p = "earless-corner-serifless"
v = "curly-serifless"
w = "straight-vertical-sides-serifless"
x = "curly-serifless"
y = "cursive-serifless"
z = "cursive"
asterisk = "turn-hex-low"
paren = "flat-arc"
brace = "curly-flat-boundary"
ampersand = "upper-open"
dollar = "open"
percent = "rings-continuous-slash"
lig-ltgteq = "slanted"

  [buildPlans.Plane.ligations]
  inherits = "javascript"

[buildPlans.Plane.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Plane.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Plane.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.Plane.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.Plane.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Plane.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
