[buildPlans.Plane]
family = "Plane"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

[buildPlans.Plane.variants.design]
capital-a = "curly-serifless"
capital-k = "straight-serifless"
capital-p = "open-serifless"
capital-r = "standing-open-serifless"
capital-v = "curly-serifless"
capital-w = "straight-vertical-sides-serifless"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "cursive"
a = "single-storey-tailed"
b = "toothless-corner-serifless"
d = "toothless-corner-serifless"
e = "rounded"
h = "tailed-serifless"
k = "straight-bottom-right-serifed"
m = "earless-rounded-double-arch-short-leg-tailed-serifless"
n = "earless-rounded-tailed-serifless"
p = "earless-corner-serifless"
v = "curly-serifless"
w = "straight-vertical-sides-serifless"
x = "curly-serifless"
y = "cursive-serifless"
z = "cursive"
six = "closed-contour"
seven = "bend-serifed"
eight = "two-circles"
nine = "closed-contour"
asterisk = "turn-hex-low"
paren = "flat-arc"
brace = "curly-flat-boundary"
ampersand = "upper-open"
dollar = "open"
percent = "rings-continuous-slash"
lig-ltgteq = "slanted"

[buildPlans.Plane.ligations]
inherits = "javascript"