[buildPlans.Plane]
exportGlyphNames = true
family = "Plane"
noCvSs = true
serifs = "sans"
spacing = "normal"

[buildPlans.Plane.variants.design]
a = "single-storey-tailed"
ampersand = "upper-open"
asterisk = "turn-hex-low"
capital-a = "curly-serifless"
capital-k = "straight-serifless"
capital-p = "open-serifless"
capital-r = "standing-open-serifless"
capital-v = "curly-serifless"
capital-w = "straight-vertical-sides-serifless"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "cursive"
dollar = "open"
e = "rounded"
eight = "two-circles"
four = "open"
g = "single-storey-serifed"
h = "tailed-serifless"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-ltgteq = "slanted"
m = "earless-rounded-double-arch-short-leg-tailed-serifless"
n = "earless-rounded-tailed-serifless"
nine = "closed-contour"
p = "earless-corner-serifless"
paren = "flat-arc"
percent = "rings-continuous-slash"
seven = "bend-serifed"
six = "closed-contour"
x = "curly-serifless"
y = "cursive-serifless"
z = "straight-serifed"

[buildPlans.Plane.ligations]
inherits = "dlig"
