[buildPlans.plane]
family = "Plane"
spacing = "fontconfig-mono"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

[buildPlans.plane.variants.design]
capital-a = "curly-serifless"
capital-k = "straight-serifless"
capital-w = "straight-vertical-sides"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "straight-serifed"
a = "single-storey-tailed"
e = "rounded"
h = "tailed"
k = "straight-bottom-right-serifed"
m = "earless-corner-double-arch-tailed"
n = "earless-rounded-tailed"
w = "straight-vertical-sides"
x = "curly-serifless"
y = "cursive"
z = "straight-serifed"
four = "open-non-crossing"
seven = "bend-serifless"
asterisk = "turn-hex-low"
caret = "high"
brace = "straight"
dollar = "open-cap"
percent = "rings-continuous-slash"
lig-ltgteq = "slanted"

[buildPlans.plane.variants.italic]
capital-z = "cursive"
g = "single-storey-serifed"
k = "cursive-serifless"
q = "diagonal-tailed"
t = "standard-short-neck2"
x = "curly-serifless"
z = "cursive"

[buildPlans.plane.variants.oblique]
capital-z = "cursive"
g = "single-storey-serifed"
k = "cursive-top-left-serifed"
q = "diagonal-tailed"
t = "standard-short-neck2"
x = "curly-serifless"
z = "cursive"

  [buildPlans.plane.ligations]
  inherits = "javascript"

[buildPlans.plane.widths.normal]
shape = 600
menu = 5
css = "normal"